version: 0.2
env:
  shell: bash
phases:
  install:
    runtime-versions:
      nodejs: 16.x
  pre_build:
    commands:
      - yarn
  build:
    commands:
      - yarn build

  post_build:
    commands:
      - aws s3 rm --recursive s3://${DEPLOY_BUCKET_NAME}
      - aws s3 sync dist s3://${DEPLOY_BUCKET_NAME} --region=ap-northeast-1
      - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths '/*'
cache:
  paths:
    - "node_modules/**/*"
